// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for the FLUMBLE Firebase project `fumble-d3387`.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ7CFJgFmNLFSeJg4NsD8zFVhOy4vWArc',
    appId: '1:798280538819:android:2465f06afda359a0142076',
    messagingSenderId: '798280538819',
    projectId: 'fumble-d3387',
    storageBucket: 'fumble-d3387.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJLhAuJvvC1wr1ihhUMsSzI8pSPLnJi8E',
    appId: '1:798280538819:ios:48211ea0a7474fc9142076',
    messagingSenderId: '798280538819',
    projectId: 'fumble-d3387',
    storageBucket: 'fumble-d3387.firebasestorage.app',
    iosBundleId: 'com.fumble.app',
  );
}
